title: Subutai Documentation
default_lang: en
author:
  name: OptDyn
  email: info@optdyn.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Subutai helps connect individuals from all over the globe so they may share resources to create secure cloud environments across their peers. Just as a cloud can float down onto land and is thus called fog, IoT devices attach when available and needed to your cloud as it floats around with you.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
