title: 'Subutai Documentation v7'
default_lang: en
author:
  name: Subutai
  email: john@email.com
taxonomies:
  - category
  - tag
  - author
metadata:
  description: 'Learn2 with Git Sync'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
